### ISSUE TITLE
Executable crash on startup [Win10]

### ISSUE THREAD

**Issue by CookieShade** [dev7355608/csgo_dont_blind_me#1]
Just downloaded the script (v. 0.2.4) and ran it, but it wouldn't start.
I tried to change `mat_monitorgamma` to 1.5, 2.2 and 3, and `mat_monitorgamma_tv_enabled`  to 1, disable f.lux and the built-in Windows night light, but it still crashed with the same message:
```
Don't forget to copy gamestate_integration_dont_blind_me.cfg into
    ...\Steam\userdata\________\730\local\cfg, or
    ...\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\cfg!

All options are set in settings.json!

Active method: GAMMA; available are GAMMA and DDC/CI.

Traceback (most recent call last):
  File "app.py", line 182, in <module>
  File "app.py", line 178, in test_gamma_ramp
  File "app.py", line 65, in set_gamma_ramp
  File "monitor.py", line 183, in set_device_gamma_ramp
OSError: [WinError 87] The parameter is incorrect.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 229, in <module>
RuntimeError: Device does not support the full gamma range
Failed to execute script app

Press any key or CTRL+C to exit...
```
If there's any extra info needed about my system, just ask.

OS: Windows 10.0.15063 (x64)

**Comment by dev7355608** [comment]
It might be fixed in the most recent release. Let me know!

**Comment by CookieShade** [comment]
Yep, it works i 0.2.6 now. Great stuff!

**Comment by p410n3** [comment]
@dev7355608 *close the issue*
